version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: can-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: can-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  init-kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Attente de Kafka...'
      while ! nc -z kafka 9092; do sleep 1; done
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic player_metrics --partitions 1 --replication-factor 1
      echo -e 'Topic créé.'
      "

  # --- PRODUCTEUR (Image légère) ---
  coach-cli:
    build:
      context: .
      dockerfile: Dockerfile.producer  # <--- UTILISE LE FICHIER LÉGER
    container_name: can-coach
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    command: python src/player_manager.py
    stdin_open: true
    tty: true

  # --- CONSOMMATEUR (Image Spark) ---
  spark-processor:
    build:
      context: .
      dockerfile: Dockerfile.consumer  # <--- UTILISE LE FICHIER LOURD (JAVA+SPARK)
    container_name: can-spark
    depends_on:
      - kafka
    restart: on-failure
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    # La commande spark-submit fonctionnera car le PATH est corrigé dans Dockerfile.consumer
    command: spark-submit --master local[*] --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 src/spark_processor.py
